INTERRUPT_VERSION = 1.0
INTERRUPT_SITE = $(TOPDIR)/package/interrupt
INTERRUPT_SITE_METHOD = local
INTERRUPT_LICENSE = GPLv3+

INTERRPUT_DEPENDENCIES = linux

define INTERRUPT_BUILD_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D)
endef

define INTERRUPT_INSTALL_TARGET_CMDS
$(MAKE) -C $(LINUX_DIR) $(LINUX_MAKE_FLAGS) M=$(@D) modules_install
endef

$(eval $(generic-package))

